controller_list:
  - name: fake_thumb_controller
    joints:
      - thumb_base_palm
      - thumb_end_to_thumb_base
  - name: fake_index_controller
    joints:
      - base_link_to_index_base
      - index_base_to_middle
      - index_middle_to_end
  - name: fake_middle_controller
    joints:
      - base_link_to_middle_base
      - middle_base_to_middle
      - middle_middle_to_end
  - name: fake_pinky_controller
    joints:
      - base_link_to_pinky_base
      - pinky_base_to_middle
      - pinky_middle_to_end
  - name: fake_ring_controller
    joints:
      - base_link_to_ring_base
      - ring_base_to_middle
      - ring_middle_to_end
initial:  # Define initial robot poses.
  - group: thumb
    pose: thumb_pose
  - group: index
    pose: index_pose
  - group: middle
    pose: middle_pose
  - group: ring
    pose: ring_pose